#include "css.h"

// Constuctor
Css::Css() {
  _css = "";
  _css.concat("a { text-decoration: none; }\n");
  _css.concat(".collapse { border-collapse: collapse; }\n");
  _css.concat(".img-xs { background-size: 10px; width: 10px; height: 10px; }\n");
  _css.concat(".img-s { background-size: 14px; width: 14px; height: 14px; }\n");
  _css.concat(".img { background-size: 18px; width: 18px; height: 18px; }\n");
  _css.concat(".img-l { background-size: 24px; width: 24px; height: 24px; }\n");
  _css.concat(".img-xl { background-size: 36px; width: 36px; height: 36px; }\n");
  _css.concat(".w100 { width: 100px; }\n");
  _css.concat(".abs { position: absolute; }\n");
  _css.concat(".rel { position: relative; }\n");
  _css.concat(".fw { width: -webkit-fill-available; }\n");
  _css.concat(".pointer { cursor: pointer; }\n");
  _css.concat(".vmiddle { vertical-align: middle; }\n");
  _css.concat(".vtop { vertical-align: top; }\n");
  _css.concat(".top-0 { top: 0px; }\n");
  _css.concat(".left-0 { left: 0px; }\n");
  _css.concat(".right-0 { right: 0px; }\n");
  _css.concat(".bottom-0 { bottom: 0px; }\n");
  _css.concat(".top-s { top: 2px; }\n");
  _css.concat(".left-s { left: 2px; }\n");
  _css.concat(".right-s { right: 2px; }\n");
  _css.concat(".bottom-s { bottom: 2px; }\n");
  _css.concat(".top { top: 5px; }\n");
  _css.concat(".left { left: 5px; }\n");
  _css.concat(".right { right: 5px; }\n");
  _css.concat(".bottom { bottom: 5px; }\n");
  _css.concat(".icon-xl { height: 40px; width: 40px; }\n");
  _css.concat(".icon-l { height: 24px; width: 24px; }\n");
  _css.concat(".icon-s { height: 18px; width: 18px; }\n");
  _css.concat(".icon-xs { height: 14px; width: 14px; }\n");
  _css.concat(".border { border-style: solid; }\n");
  _css.concat(".borderb-d { border-bottom: dotted; }\n");
  _css.concat(".border-n { border-style: none; }\n");
  _css.concat(".bordert-n { border-top: none; }\n");
  _css.concat(".borderl-n { border-left: none; }\n");
  _css.concat(".border-gray-d { border-color: #6C6C6C; }\n");
  _css.concat(".border-red { border-color: #c5441d }\n");
  _css.concat(".border-blue { border-color: #1c74e1 }\n");
  _css.concat(".border-white { border-color: #FFFFFF }\n");
  _css.concat(".border-green { border-color: #b7d51c }\n");
  _css.concat(".circle { border-radius: 50% 50% 50% 50%; }\n");
  _css.concat(".gray-l { background: #C0C0C0; }\n");
  _css.concat(".gray { background: #AEAEAE; }\n");
  _css.concat(".gray-d { background: #6C6C6C; }\n");
  _css.concat(".white { background: #FFFFFF; }\n");
  _css.concat(".red { background: #c5441d; }\n");
  _css.concat(".yellow-l { background: #d7ad4a; }\n");
  _css.concat(".yellow { background: #cd981d; }\n");
  _css.concat(".yellow-d { background: #b9891a; }\n");
  _css.concat(".trans { background: transparent; }\n");
  _css.concat(".green-l { background: #cde260; }\n");
  _css.concat(".green { background: #b7d51c; }\n");
  _css.concat(".green-d { background: #92aa16; }\n");
  _css.concat(".blue { background: #1c74e1; }\n");
  _css.concat(".black { background: #000000; }\n");
  _css.concat(".text-white { color: #FFFFFF; }\n");
  _css.concat(".text-gray-l { color: #C0C0C0; }\n");
  _css.concat(".text-gray { color: #AEAEAE; }\n");
  _css.concat(".text-gray-d { color: #6C6C6C; }\n");
  _css.concat(".text-red { color: #c5441d; }\n");
  _css.concat(".text-black { color: #000000; }\n");
  _css.concat(".text-blue { color: #1c74e1; }\n");
  _css.concat(".text-green { color: #b7d51c; }\n");
  _css.concat(".text-yellow { color: #cd981d; }\n");
  _css.concat(".tc { text-align: center; }\n");
  _css.concat(".tl { text-align: left; }\n");
  _css.concat(".tr { text-align: right; }\n");
  _css.concat(".b { font-weight: bold; }\n");
  _css.concat(".fs-xxs { font-size: 10px; }\n");
  _css.concat(".fs-xs { font-size: 12px; }\n");
  _css.concat(".fs-s { font-size: 14px; }\n");
  _css.concat(".fs-m { font-size: 16px; }\n");
  _css.concat(".fs-l { font-size: 18px; }\n");
  _css.concat(".fs-xl { font-size: 20px; }\n");
  _css.concat(".fs-xxl { font-size: 22px; }\n");
  _css.concat(".icon { height: 16px; width: 16px; }\n");
  _css.concat(".square { height: 52px; width: 52px; }\n");
  _css.concat(".squarem { height: 52px; min-width: 52px; }\n");
  _css.concat(".square-s { height: 26px; width: 26px; }\n");
  _css.concat(".squarem-s { height: 26px; min-width: 26px; }\n");
  _css.concat(".pad { padding: 5px; }\n");
  _css.concat(".pad-l { padding: 10px; }\n");
  _css.concat(".pad-s { padding: 2px; }\n");
  _css.concat(".pad-0 { padding: 0px; }\n");
  _css.concat(".padx { padding-left: 5px; padding-right: 5px; }\n");
  _css.concat(".padx-s { padding-left: 2px; padding-right: 2px; }\n");
  _css.concat(".padl-s { padding-left: 2px; }\n");
  _css.concat(".mar-s { margin: 2px; }\n");
  _css.concat(".mart-s { margin-top: 2px; }\n");
  _css.concat(".mar { margin: 5px; }\n");
  _css.concat(".marl { margin-left: 5px; }\n");
  _css.concat(".mar-0 { margin: 0px; }\n");
  _css.concat(".marb { margin-bottom: 5px; }\n");
  _css.concat(".mar-l { margin: 10px; }\n");
  _css.concat(".marr { margin-right: 5px; }\n");
  _css.concat(".mart { margin-top: 5px; }\n");
  _css.concat(".radius { border-radius: 5px; }\n");
  _css.concat(".radiust { border-radius: 5px 5px 0px 0px; }\n");
  _css.concat(".radiusb { border-radius: 0px 0px 5px 5px; }\n");
  _css.concat(".radiustl { border-radius: 5px 0px 0px 0px; }\n");
  _css.concat(".radiustr { border-radius: 0px 5px 0px 0px; }\n");
  _css.concat(".radiusbr { border-radius: 0px 0px 5px 0px; }\n");
  _css.concat(".radiusbl { border-radius: 0px 0px 0px 5px; }\n");
  _css.concat(".radiusl { border-radius: 5px 0px 0px 5px; }\n");
  _css.concat(".radiusr { border-radius: 0px 5px 5px 0px; }\n");
  _css.concat(".radius-l { border-radius: 10px; }\n");
  _css.concat(".radiusl-l { border-radius: 10px 0px 0px 10px; }\n");
  _css.concat(".radiusr-l { border-radius: 0px 10px 10px 0px; }\n");
  _css.concat(".it {font-style: italic; }\n");
  _css.concat(".i { display: inline; }\n");
  _css.concat(".ib { display: inline-block; }\n");
  _css.concat(".if { display: inline-flex; }\n");
  _css.concat(".f { display: flex; }\n");
  _css.concat(".col { flex-direction: column; }\n");
  _css.concat(".g-0 { gap: 0px; }\n");
  _css.concat(".g-s { gap: 2px; }\n");
  _css.concat(".g { gap: 5px; }\n");
  _css.concat(".g-l { gap: 10px; }\n");
  _css.concat(".g-xl { gap: 16px; }\n");
  _css.concat(".ai-s { align-items: start; }\n");
  _css.concat(".ai-c { align-items: center; }\n");
  _css.concat(".m-auto { margin: auto; }\n");
}

// Public
String Css::getCSS() {
  return _css;
}